### ISSUE TITLE
Autopublish for release branches

### ISSUE THREAD

**Issue by Frostman** [githedgehog/docs#59]

**Comment by qmonnet** [comment]
I'm curious, how do you plan to handle release branches and publishing from these?

**Comment by Frostman** [comment]
> I'm curious, how do you plan to handle release branches and publishing from these?

we already have a setup itself working for publishing versioned docs using branches (using mkdocs and https://github.com/jimporter/mike ), the only thing missing is to run corresponding job in CI to publish from the release branches, right now it's only happening from the master
